# -*- coding: utf-8 -*-
"""MT5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJ12Aaa4TYKz3VhLQEfeg8XwsRTXsGBu
"""

!pip install -q transformers datasets evaluate rouge-score fastapi pyngrok uvicorn nest-asyncio

import os
import glob
import warnings
import threading
from pathlib import Path
import torch
import pandas as pd
import numpy as np
from tqdm import tqdm

from transformers import (pipeline,AutoTokenizer,AutoModelForSeq2SeqLM,
                          Seq2SeqTrainingArguments,Seq2SeqTrainer)
from datasets import Dataset
import evaluate

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import nest_asyncio
from pyngrok import ngrok
import uvicorn

# Suppress warnings
warnings.filterwarnings('ignore')
os.environ['TOKENIZERS_PARALLELISM'] = 'false'

# Configure device
DEVICE = 0 if torch.cuda.is_available() else -1
print(f"✓ Using device: {'GPU (CUDA)' if DEVICE == 0 else 'CPU'}")

from google.colab import drive
import zipfile
import os

# Mount Google Drive
drive.mount('/content/drive', force_remount=True)

# Define paths
ZIP_PATH = "/content/drive/MyDrive/Colab Notebooks/MT5/archive (2).zip"
EXTRACT_TO = "/content/drive/MyDrive/Colab Notebooks/MT5/"

# Unzip the dataset
with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
    zip_ref.extractall(EXTRACT_TO)

# Define article and summary paths
bbc_path = os.path.join(EXTRACT_TO, 'BBC News Summary')
ARTICLES_PATH = os.path.join(bbc_path, 'News Articles')
SUMMARIES_PATH = os.path.join(bbc_path, 'Summaries')

def load_bbc_dataset(articles_path: str, summaries_path: str) -> pd.DataFrame:
    """
    Load BBC News dataset from disk.

    Args:
        articles_path: Path to articles directory
        summaries_path: Path to summaries directory

    Returns:
        DataFrame with 'article' and 'summary' columns
    """
    articles_dict = {}
    summaries_dict = {}

    # Load articles
    for txt_file in glob.glob(os.path.join(articles_path, '**/*.txt'), recursive=True):
        file_id = os.path.basename(txt_file)
        try:
            with open(txt_file, 'r', encoding='utf-8', errors='ignore') as f:
                articles_dict[file_id] = f.read().strip()
        except Exception as e:
            print(f"Warning: Failed to read {txt_file}: {e}")

    # Load summaries
    for txt_file in glob.glob(os.path.join(summaries_path, '**/*.txt'), recursive=True):
        file_id = os.path.basename(txt_file)
        try:
            with open(txt_file, 'r', encoding='utf-8', errors='ignore') as f:
                summaries_dict[file_id] = f.read().strip()
        except Exception as e:
            print(f"Warning: Failed to read {txt_file}: {e}")

    # Match articles with summaries
    data = []
    for file_id in articles_dict:
        if file_id in summaries_dict:
            data.append({
                'article': articles_dict[file_id],
                'summary': summaries_dict[file_id]
            })

    df = pd.DataFrame(data)
    print(f"✓ Loaded {len(df)} article-summary pairs")

    return df

# Load dataset
df = load_bbc_dataset(ARTICLES_PATH, SUMMARIES_PATH)

# Initialize baseline T5-small model
baseline_summarizer = pipeline(
    "summarization",
    model="t5-small",
    device=DEVICE
)

print("✓ Baseline model loaded")

# Evaluate baseline on sample
sample_df = df.sample(n=5, random_state=42).reset_index(drop=True)

baseline_summaries = []
for article in tqdm(sample_df['article'], desc="Baseline evaluation"):
    summary = baseline_summarizer(
        article,
        max_length=130,
        min_length=30,
        do_sample=False
    )
    baseline_summaries.append(summary[0]['summary_text'])

sample_df['baseline_summary'] = baseline_summaries

# Calculate baseline ROUGE scores
rouge = evaluate.load('rouge')
baseline_results = rouge.compute(
    predictions=baseline_summaries,
    references=sample_df['summary'].tolist()
)

print("\n" + "="*50)
print("BASELINE MODEL PERFORMANCE")
print("="*50)
print(f"ROUGE-1: {baseline_results['rouge1']:.4f}")
print(f"ROUGE-2: {baseline_results['rouge2']:.4f}")
print(f"ROUGE-L: {baseline_results['rougeL']:.4f}")
print("="*50)

# Configuration
MODEL_NAME = "t5-small"
TRAIN_SIZE = 500
OUTPUT_DIR = "./fine_tuned_t5"

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

# Prepare training dataset
train_df = df.sample(n=min(TRAIN_SIZE, len(df)), random_state=42).reset_index(drop=True)
train_dataset = Dataset.from_pandas(train_df[['article', 'summary']])

print(f"✓ Training on {len(train_df)} samples")

def preprocess_function(examples):
    """Tokenize articles and summaries for T5."""
    inputs = ["summarize: " + doc for doc in examples['article']]
    model_inputs = tokenizer(
        inputs,
        max_length=512,
        truncation=True,
        padding="max_length"
    )

    labels = tokenizer(
        examples['summary'],
        max_length=128,
        truncation=True,
        padding="max_length"
    )
    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

# Tokenize dataset
tokenized_dataset = train_dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=['article', 'summary'],
    desc="Tokenizing"
)

print("✓ Dataset tokenized")

# Training configuration
training_args = Seq2SeqTrainingArguments(
    output_dir=OUTPUT_DIR,
    eval_strategy="no",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    save_total_limit=1,
    predict_with_generate=True,
    fp16=torch.cuda.is_available(),
    logging_steps=50,
    report_to="none"  # Disable wandb logging
)

# Initialize trainer
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    processing_class=tokenizer,
)

print("✓ Trainer initialized")
print("\nStarting training (estimated 5-10 minutes)...\n")

# Train model
trainer.train()

# Save model
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print(f"\n✓ Fine-tuning complete! Model saved to {OUTPUT_DIR}")

# Load fine-tuned model
finetuned_summarizer = pipeline(
    "summarization",
    model=OUTPUT_DIR,
    tokenizer=OUTPUT_DIR,
    device=DEVICE
)

print("✓ Fine-tuned model loaded")

# Test on unseen samples
test_df = df[~df.index.isin(train_df.index)].sample(n=5, random_state=99).reset_index(drop=True)

finetuned_summaries = []
for article in tqdm(test_df['article'], desc="Fine-tuned evaluation"):
    summary = finetuned_summarizer(
        "summarize: " + article,
        max_length=130,
        min_length=30,
        do_sample=False
    )
    finetuned_summaries.append(summary[0]['summary_text'])

test_df['finetuned_summary'] = finetuned_summaries

# Calculate fine-tuned ROUGE scores
finetuned_results = rouge.compute(
    predictions=finetuned_summaries,
    references=test_df['summary'].tolist()
)

# Display comparison
print("\n" + "="*60)
print("MODEL PERFORMANCE COMPARISON")
print("="*60)
print(f"{'Metric':<12} {'Baseline':<12} {'Fine-tuned':<12} {'Δ':<12}")
print("-"*60)
print(f"{'ROUGE-1':<12} {baseline_results['rouge1']:<12.4f} {finetuned_results['rouge1']:<12.4f} {finetuned_results['rouge1']-baseline_results['rouge1']:+.4f}")
print(f"{'ROUGE-2':<12} {baseline_results['rouge2']:<12.4f} {finetuned_results['rouge2']:<12.4f} {finetuned_results['rouge2']-baseline_results['rouge2']:+.4f}")
print(f"{'ROUGE-L':<12} {baseline_results['rougeL']:<12.4f} {finetuned_results['rougeL']:<12.4f} {finetuned_results['rougeL']-baseline_results['rougeL']:+.4f}")
print("="*60)

# Show example
print("\nEXAMPLE OUTPUT:")
print("="*80)
print(f"Reference: {test_df['summary'].iloc[0][:150]}...")
print(f"\nGenerated: {test_df['finetuned_summary'].iloc[0]}")

import matplotlib.pyplot as plt
import numpy as np

# ============================================
# 1. TRAINING LOSS CURVE
# ============================================
# Extract training loss from trainer history
log_history = trainer.state.log_history
train_losses = [log['loss'] for log in log_history if 'loss' in log]
train_steps = [log['step'] for log in log_history if 'loss' in log]

plt.figure(figsize=(10, 6))
plt.plot(train_steps, train_losses, linewidth=2.5, color='#2E86AB', marker='o', markersize=4)
plt.title('Training Loss Over Time', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Training Steps', fontsize=12, fontweight='bold')
plt.ylabel('Loss', fontsize=12, fontweight='bold')
plt.grid(True, alpha=0.3, linestyle='--')
plt.tight_layout()
plt.savefig('training_loss_curve.png', dpi=300, bbox_inches='tight')
print("✓ Saved: training_loss_curve.png")
plt.show()

# ============================================
# 2. ROUGE SCORE COMPARISON BAR CHART
# ============================================
metrics = ['ROUGE-1', 'ROUGE-2', 'ROUGE-L']
baseline_scores = [
    baseline_results['rouge1'],
    baseline_results['rouge2'],
    baseline_results['rougeL']
]
finetuned_scores = [
    finetuned_results['rouge1'],
    finetuned_results['rouge2'],
    finetuned_results['rougeL']
]

x = np.arange(len(metrics))
width = 0.35

fig, ax = plt.subplots(figsize=(12, 7))
bars1 = ax.bar(x - width/2, baseline_scores, width, label='Baseline (T5-small)',
               color='#E63946', alpha=0.8, edgecolor='black', linewidth=1.2)
bars2 = ax.bar(x + width/2, finetuned_scores, width, label='Fine-tuned',
               color='#06D6A0', alpha=0.8, edgecolor='black', linewidth=1.2)

# Add value labels on bars
for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.4f}',
                ha='center', va='bottom', fontsize=10, fontweight='bold')

# Calculate and display improvement percentages
for i, (baseline, finetuned) in enumerate(zip(baseline_scores, finetuned_scores)):
    improvement = ((finetuned - baseline) / baseline) * 100
    ax.text(i, max(baseline, finetuned) + 0.02,
            f'+{improvement:.1f}%',
            ha='center', va='bottom', fontsize=11, fontweight='bold', color='#2A9D8F')

ax.set_xlabel('Metrics', fontsize=13, fontweight='bold')
ax.set_ylabel('Score', fontsize=13, fontweight='bold')
ax.set_title('Model Performance: Baseline vs Fine-tuned', fontsize=16, fontweight='bold', pad=20)
ax.set_xticks(x)
ax.set_xticklabels(metrics, fontsize=12)
ax.legend(fontsize=11, loc='upper left', framealpha=0.9)
ax.grid(True, alpha=0.3, linestyle='--', axis='y')
ax.set_ylim(0, max(max(baseline_scores), max(finetuned_scores)) + 0.08)

plt.tight_layout()
plt.savefig('rouge_comparison.png', dpi=300, bbox_inches='tight')
print("✓ Saved: rouge_comparison.png")
plt.show()

print("\n" + "="*60)
print("📊 VISUALIZATIONS CREATED SUCCESSFULLY!")
print("="*60)
print("Files saved:")
print("  1. training_loss_curve.png")
print("  2. rouge_comparison.png")
print("\nReady for your LinkedIn post! 🚀")
print("="*60)



!pip install -q gradio

import gradio as gr

def summarize_text(article, max_length=130, min_length=30):
    """Generate summary using fine-tuned model."""
    if not article.strip():
        return "⚠️ Please enter some text to summarize."

    try:
        summary = finetuned_summarizer(
            "summarize: " + article,
            max_length=int(max_length),
            min_length=int(min_length),
            do_sample=False
        )
        return summary[0]['summary_text']
    except Exception as e:
        return f"❌ Error: {str(e)}"

# Sample article for demo
sample_article = """The government has announced new measures to tackle climate change.
The plan includes reducing carbon emissions by 50% by 2030 and investing heavily in
renewable energy sources. Environmental groups have welcomed the move, calling it a
significant step forward. However, some industry leaders have expressed concerns about
the economic impact of such rapid changes."""

# Create Gradio interface
demo = gr.Interface(
    fn=summarize_text,
    inputs=[
        gr.Textbox(
            label="📰 Input Article",
            placeholder="Paste your article here...",
            lines=10,
            value=sample_article
        ),
        gr.Slider(
            minimum=50,
            maximum=200,
            value=130,
            step=10,
            label="Max Summary Length"
        ),
        gr.Slider(
            minimum=20,
            maximum=100,
            value=30,
            step=5,
            label="Min Summary Length"
        )
    ],
    outputs=gr.Textbox(label="✨ Generated Summary", lines=5),
    title="📝 T5 News Summarizer",
    description="Fine-tuned T5 model for BBC News summarization. Paste an article and get an instant summary!",
    examples=[
        [sample_article, 130, 30],
        ["Technology companies are racing to develop artificial intelligence systems. Major investments are being made in machine learning research.", 100, 30]
    ],
    theme=gr.themes.Soft()

# Launch interface
demo.launch(share=True, debug=True)

print("\n🚀 Interface launched!")

